// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog.proto

package edu

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetCatalogRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCatalogRequest) Reset()         { *m = GetCatalogRequest{} }
func (m *GetCatalogRequest) String() string { return proto.CompactTextString(m) }
func (*GetCatalogRequest) ProtoMessage()    {}
func (*GetCatalogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_2888b1efe1dfe822, []int{0}
}
func (m *GetCatalogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCatalogRequest.Unmarshal(m, b)
}
func (m *GetCatalogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCatalogRequest.Marshal(b, m, deterministic)
}
func (dst *GetCatalogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCatalogRequest.Merge(dst, src)
}
func (m *GetCatalogRequest) XXX_Size() int {
	return xxx_messageInfo_GetCatalogRequest.Size(m)
}
func (m *GetCatalogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCatalogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCatalogRequest proto.InternalMessageInfo

type GetCatalogReply struct {
	Courses              []*Course `protobuf:"bytes,1,rep,name=courses" json:"courses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCatalogReply) Reset()         { *m = GetCatalogReply{} }
func (m *GetCatalogReply) String() string { return proto.CompactTextString(m) }
func (*GetCatalogReply) ProtoMessage()    {}
func (*GetCatalogReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_2888b1efe1dfe822, []int{1}
}
func (m *GetCatalogReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCatalogReply.Unmarshal(m, b)
}
func (m *GetCatalogReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCatalogReply.Marshal(b, m, deterministic)
}
func (dst *GetCatalogReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCatalogReply.Merge(dst, src)
}
func (m *GetCatalogReply) XXX_Size() int {
	return xxx_messageInfo_GetCatalogReply.Size(m)
}
func (m *GetCatalogReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCatalogReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetCatalogReply proto.InternalMessageInfo

func (m *GetCatalogReply) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

type GetCourseRequest struct {
	CourseId             uint64   `protobuf:"varint,1,opt,name=course_id,json=courseId" json:"course_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCourseRequest) Reset()         { *m = GetCourseRequest{} }
func (m *GetCourseRequest) String() string { return proto.CompactTextString(m) }
func (*GetCourseRequest) ProtoMessage()    {}
func (*GetCourseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_2888b1efe1dfe822, []int{2}
}
func (m *GetCourseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCourseRequest.Unmarshal(m, b)
}
func (m *GetCourseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCourseRequest.Marshal(b, m, deterministic)
}
func (dst *GetCourseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCourseRequest.Merge(dst, src)
}
func (m *GetCourseRequest) XXX_Size() int {
	return xxx_messageInfo_GetCourseRequest.Size(m)
}
func (m *GetCourseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCourseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCourseRequest proto.InternalMessageInfo

func (m *GetCourseRequest) GetCourseId() uint64 {
	if m != nil {
		return m.CourseId
	}
	return 0
}

type GetCourseReply struct {
	Course               *Course  `protobuf:"bytes,1,opt,name=course" json:"course,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCourseReply) Reset()         { *m = GetCourseReply{} }
func (m *GetCourseReply) String() string { return proto.CompactTextString(m) }
func (*GetCourseReply) ProtoMessage()    {}
func (*GetCourseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_2888b1efe1dfe822, []int{3}
}
func (m *GetCourseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCourseReply.Unmarshal(m, b)
}
func (m *GetCourseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCourseReply.Marshal(b, m, deterministic)
}
func (dst *GetCourseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCourseReply.Merge(dst, src)
}
func (m *GetCourseReply) XXX_Size() int {
	return xxx_messageInfo_GetCourseReply.Size(m)
}
func (m *GetCourseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCourseReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetCourseReply proto.InternalMessageInfo

func (m *GetCourseReply) GetCourse() *Course {
	if m != nil {
		return m.Course
	}
	return nil
}

type Lesson struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Position             float32  `protobuf:"fixed32,3,opt,name=position" json:"position,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	PublishedUtc         string   `protobuf:"bytes,5,opt,name=published_utc,json=publishedUtc" json:"published_utc,omitempty"`
	CreatedBy            uint64   `protobuf:"varint,6,opt,name=created_by,json=createdBy" json:"created_by,omitempty"`
	UpdatedBy            uint64   `protobuf:"varint,7,opt,name=updated_by,json=updatedBy" json:"updated_by,omitempty"`
	UpdatedUtc           string   `protobuf:"bytes,8,opt,name=updated_utc,json=updatedUtc" json:"updated_utc,omitempty"`
	Deleted              bool     `protobuf:"varint,9,opt,name=deleted" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lesson) Reset()         { *m = Lesson{} }
func (m *Lesson) String() string { return proto.CompactTextString(m) }
func (*Lesson) ProtoMessage()    {}
func (*Lesson) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_2888b1efe1dfe822, []int{4}
}
func (m *Lesson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lesson.Unmarshal(m, b)
}
func (m *Lesson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lesson.Marshal(b, m, deterministic)
}
func (dst *Lesson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lesson.Merge(dst, src)
}
func (m *Lesson) XXX_Size() int {
	return xxx_messageInfo_Lesson.Size(m)
}
func (m *Lesson) XXX_DiscardUnknown() {
	xxx_messageInfo_Lesson.DiscardUnknown(m)
}

var xxx_messageInfo_Lesson proto.InternalMessageInfo

func (m *Lesson) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Lesson) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Lesson) GetPosition() float32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *Lesson) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Lesson) GetPublishedUtc() string {
	if m != nil {
		return m.PublishedUtc
	}
	return ""
}

func (m *Lesson) GetCreatedBy() uint64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *Lesson) GetUpdatedBy() uint64 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

func (m *Lesson) GetUpdatedUtc() string {
	if m != nil {
		return m.UpdatedUtc
	}
	return ""
}

func (m *Lesson) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type Chapter struct {
	Id                   uint64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Position             float32   `protobuf:"fixed32,3,opt,name=position" json:"position,omitempty"`
	PublishedUtc         string    `protobuf:"bytes,4,opt,name=published_utc,json=publishedUtc" json:"published_utc,omitempty"`
	CreatedBy            uint64    `protobuf:"varint,5,opt,name=created_by,json=createdBy" json:"created_by,omitempty"`
	UpdatedBy            uint64    `protobuf:"varint,6,opt,name=updated_by,json=updatedBy" json:"updated_by,omitempty"`
	UpdatedUtc           string    `protobuf:"bytes,7,opt,name=updated_utc,json=updatedUtc" json:"updated_utc,omitempty"`
	Deleted              bool      `protobuf:"varint,8,opt,name=deleted" json:"deleted,omitempty"`
	Lessons              []*Lesson `protobuf:"bytes,9,rep,name=lessons" json:"lessons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Chapter) Reset()         { *m = Chapter{} }
func (m *Chapter) String() string { return proto.CompactTextString(m) }
func (*Chapter) ProtoMessage()    {}
func (*Chapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_2888b1efe1dfe822, []int{5}
}
func (m *Chapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chapter.Unmarshal(m, b)
}
func (m *Chapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chapter.Marshal(b, m, deterministic)
}
func (dst *Chapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chapter.Merge(dst, src)
}
func (m *Chapter) XXX_Size() int {
	return xxx_messageInfo_Chapter.Size(m)
}
func (m *Chapter) XXX_DiscardUnknown() {
	xxx_messageInfo_Chapter.DiscardUnknown(m)
}

var xxx_messageInfo_Chapter proto.InternalMessageInfo

func (m *Chapter) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Chapter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Chapter) GetPosition() float32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *Chapter) GetPublishedUtc() string {
	if m != nil {
		return m.PublishedUtc
	}
	return ""
}

func (m *Chapter) GetCreatedBy() uint64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *Chapter) GetUpdatedBy() uint64 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

func (m *Chapter) GetUpdatedUtc() string {
	if m != nil {
		return m.UpdatedUtc
	}
	return ""
}

func (m *Chapter) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Chapter) GetLessons() []*Lesson {
	if m != nil {
		return m.Lessons
	}
	return nil
}

type Course struct {
	Id                   uint64     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Decription           string     `protobuf:"bytes,3,opt,name=decription" json:"decription,omitempty"`
	PublishedUtc         string     `protobuf:"bytes,4,opt,name=published_utc,json=publishedUtc" json:"published_utc,omitempty"`
	CreatedBy            uint64     `protobuf:"varint,5,opt,name=created_by,json=createdBy" json:"created_by,omitempty"`
	UpdatedBy            uint64     `protobuf:"varint,6,opt,name=updated_by,json=updatedBy" json:"updated_by,omitempty"`
	UpdatedUtc           string     `protobuf:"bytes,7,opt,name=updated_utc,json=updatedUtc" json:"updated_utc,omitempty"`
	Deleted              bool       `protobuf:"varint,8,opt,name=deleted" json:"deleted,omitempty"`
	Chapters             []*Chapter `protobuf:"bytes,9,rep,name=Chapters,json=chapters" json:"Chapters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Course) Reset()         { *m = Course{} }
func (m *Course) String() string { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()    {}
func (*Course) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_2888b1efe1dfe822, []int{6}
}
func (m *Course) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Course.Unmarshal(m, b)
}
func (m *Course) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Course.Marshal(b, m, deterministic)
}
func (dst *Course) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Course.Merge(dst, src)
}
func (m *Course) XXX_Size() int {
	return xxx_messageInfo_Course.Size(m)
}
func (m *Course) XXX_DiscardUnknown() {
	xxx_messageInfo_Course.DiscardUnknown(m)
}

var xxx_messageInfo_Course proto.InternalMessageInfo

func (m *Course) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Course) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Course) GetDecription() string {
	if m != nil {
		return m.Decription
	}
	return ""
}

func (m *Course) GetPublishedUtc() string {
	if m != nil {
		return m.PublishedUtc
	}
	return ""
}

func (m *Course) GetCreatedBy() uint64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *Course) GetUpdatedBy() uint64 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

func (m *Course) GetUpdatedUtc() string {
	if m != nil {
		return m.UpdatedUtc
	}
	return ""
}

func (m *Course) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Course) GetChapters() []*Chapter {
	if m != nil {
		return m.Chapters
	}
	return nil
}

func init() {
	proto.RegisterType((*GetCatalogRequest)(nil), "edu.GetCatalogRequest")
	proto.RegisterType((*GetCatalogReply)(nil), "edu.GetCatalogReply")
	proto.RegisterType((*GetCourseRequest)(nil), "edu.GetCourseRequest")
	proto.RegisterType((*GetCourseReply)(nil), "edu.GetCourseReply")
	proto.RegisterType((*Lesson)(nil), "edu.Lesson")
	proto.RegisterType((*Chapter)(nil), "edu.Chapter")
	proto.RegisterType((*Course)(nil), "edu.Course")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Catalog service

type CatalogClient interface {
	GetFullCatalog(ctx context.Context, in *GetCatalogRequest, opts ...grpc.CallOption) (*GetCatalogReply, error)
	ListCatalog(ctx context.Context, in *GetCatalogRequest, opts ...grpc.CallOption) (*GetCatalogReply, error)
	GetCourse(ctx context.Context, in *GetCourseRequest, opts ...grpc.CallOption) (*GetCourseReply, error)
}

type catalogClient struct {
	cc *grpc.ClientConn
}

func NewCatalogClient(cc *grpc.ClientConn) CatalogClient {
	return &catalogClient{cc}
}

func (c *catalogClient) GetFullCatalog(ctx context.Context, in *GetCatalogRequest, opts ...grpc.CallOption) (*GetCatalogReply, error) {
	out := new(GetCatalogReply)
	err := grpc.Invoke(ctx, "/edu.Catalog/GetFullCatalog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) ListCatalog(ctx context.Context, in *GetCatalogRequest, opts ...grpc.CallOption) (*GetCatalogReply, error) {
	out := new(GetCatalogReply)
	err := grpc.Invoke(ctx, "/edu.Catalog/ListCatalog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetCourse(ctx context.Context, in *GetCourseRequest, opts ...grpc.CallOption) (*GetCourseReply, error) {
	out := new(GetCourseReply)
	err := grpc.Invoke(ctx, "/edu.Catalog/GetCourse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Catalog service

type CatalogServer interface {
	GetFullCatalog(context.Context, *GetCatalogRequest) (*GetCatalogReply, error)
	ListCatalog(context.Context, *GetCatalogRequest) (*GetCatalogReply, error)
	GetCourse(context.Context, *GetCourseRequest) (*GetCourseReply, error)
}

func RegisterCatalogServer(s *grpc.Server, srv CatalogServer) {
	s.RegisterService(&_Catalog_serviceDesc, srv)
}

func _Catalog_GetFullCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetFullCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edu.Catalog/GetFullCatalog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetFullCatalog(ctx, req.(*GetCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_ListCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).ListCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edu.Catalog/ListCatalog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).ListCatalog(ctx, req.(*GetCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_GetCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edu.Catalog/GetCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetCourse(ctx, req.(*GetCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Catalog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "edu.Catalog",
	HandlerType: (*CatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFullCatalog",
			Handler:    _Catalog_GetFullCatalog_Handler,
		},
		{
			MethodName: "ListCatalog",
			Handler:    _Catalog_ListCatalog_Handler,
		},
		{
			MethodName: "GetCourse",
			Handler:    _Catalog_GetCourse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog.proto",
}

func init() { proto.RegisterFile("catalog.proto", fileDescriptor_catalog_2888b1efe1dfe822) }

var fileDescriptor_catalog_2888b1efe1dfe822 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0x4d, 0x8b, 0xd4, 0x30,
	0x18, 0xb6, 0x9d, 0xd9, 0x7e, 0xbc, 0xdd, 0x5d, 0x35, 0xab, 0x12, 0x46, 0xd4, 0xd2, 0x45, 0xe8,
	0x69, 0x84, 0x15, 0x41, 0x0f, 0x82, 0xec, 0x80, 0x22, 0xec, 0x29, 0xe0, 0x79, 0xe8, 0x34, 0x2f,
	0x6e, 0xa1, 0xb6, 0xb1, 0x49, 0x0e, 0xbd, 0xf9, 0x0b, 0x3c, 0xf9, 0x97, 0xfc, 0x5f, 0xd2, 0xa4,
	0x29, 0x75, 0x07, 0x76, 0x44, 0x2f, 0xde, 0x9a, 0xe7, 0xc9, 0x93, 0xb7, 0xcf, 0xfb, 0x05, 0x27,
	0x65, 0xa1, 0x8a, 0xba, 0xfd, 0xbc, 0x16, 0x5d, 0xab, 0x5a, 0xb2, 0x40, 0xae, 0xb3, 0x33, 0xb8,
	0xff, 0x01, 0xd5, 0xc6, 0x12, 0x0c, 0xbf, 0x6a, 0x94, 0x2a, 0x7b, 0x0d, 0x77, 0xe7, 0xa0, 0xa8,
	0x7b, 0xf2, 0x1c, 0xc2, 0xb2, 0xd5, 0x9d, 0x44, 0x49, 0xbd, 0x74, 0x91, 0x27, 0x17, 0xc9, 0x1a,
	0xb9, 0x5e, 0x6f, 0x0c, 0xc6, 0x1c, 0x97, 0xbd, 0x80, 0x7b, 0x83, 0xd2, 0xa2, 0xf6, 0x35, 0xf2,
	0x18, 0x62, 0x4b, 0x6f, 0x2b, 0x4e, 0xbd, 0xd4, 0xcb, 0x97, 0x2c, 0xb2, 0xc0, 0x47, 0x9e, 0xbd,
	0x82, 0xd3, 0x99, 0x60, 0x88, 0x74, 0x0e, 0x81, 0x65, 0xcd, 0xdd, 0x1b, 0x81, 0x46, 0x2a, 0xfb,
	0xe6, 0x43, 0x70, 0x85, 0x52, 0xb6, 0x0d, 0x39, 0x05, 0x7f, 0x7a, 0xd7, 0xaf, 0x38, 0x21, 0xb0,
	0x6c, 0x8a, 0x2f, 0x48, 0xfd, 0xd4, 0xcb, 0x63, 0x66, 0xbe, 0xc9, 0x0a, 0x22, 0xd1, 0xca, 0x4a,
	0x55, 0x6d, 0x43, 0x17, 0xa9, 0x97, 0xfb, 0x6c, 0x3a, 0x13, 0x3a, 0x38, 0x6b, 0x14, 0x36, 0x8a,
	0x2e, 0x8d, 0xc4, 0x1d, 0xc9, 0x39, 0x9c, 0x08, 0xbd, 0xab, 0x2b, 0x79, 0x8d, 0x7c, 0xab, 0x55,
	0x49, 0x8f, 0x0c, 0x7f, 0x3c, 0x81, 0x9f, 0x54, 0x49, 0x9e, 0x00, 0x94, 0x1d, 0x16, 0x0a, 0xf9,
	0x76, 0xd7, 0xd3, 0xc0, 0xfc, 0x46, 0x3c, 0x22, 0x97, 0xfd, 0x40, 0x6b, 0xc1, 0x1d, 0x1d, 0x5a,
	0x7a, 0x44, 0x2e, 0x7b, 0xf2, 0x0c, 0x12, 0x47, 0x0f, 0x01, 0x22, 0x13, 0xc0, 0x29, 0x86, 0xe7,
	0x29, 0x84, 0x1c, 0x6b, 0x54, 0xc8, 0x69, 0x9c, 0x7a, 0x79, 0xc4, 0xdc, 0x31, 0xfb, 0xee, 0x43,
	0xb8, 0xb9, 0x2e, 0x84, 0xc2, 0xee, 0x9f, 0x73, 0xb0, 0xe7, 0x74, 0x79, 0xd0, 0xe9, 0xd1, 0xed,
	0x4e, 0x83, 0x03, 0x4e, 0xc3, 0xdb, 0x9c, 0x46, 0xbf, 0x39, 0x1d, 0x7a, 0xaf, 0x36, 0xb5, 0x96,
	0x34, 0x9e, 0xf5, 0x9e, 0xad, 0x3f, 0x73, 0x5c, 0xf6, 0xc3, 0x87, 0xc0, 0xb6, 0xc9, 0x1f, 0xe5,
	0xe3, 0x29, 0x00, 0xc7, 0xb2, 0xab, 0xc4, 0x94, 0x91, 0x98, 0xcd, 0x90, 0xff, 0x3c, 0x27, 0x39,
	0x44, 0x63, 0xf1, 0x5d, 0x52, 0x8e, 0xed, 0x9c, 0x58, 0x90, 0x45, 0xe5, 0xc8, 0x5e, 0xfc, 0xf4,
	0x20, 0x1c, 0x47, 0x99, 0xbc, 0x33, 0xd3, 0xf6, 0x5e, 0xd7, 0xb5, 0x43, 0x1e, 0x19, 0xd5, 0xde,
	0x0a, 0x58, 0x3d, 0xd8, 0xc3, 0x45, 0xdd, 0x67, 0x77, 0xc8, 0x5b, 0x48, 0xae, 0x2a, 0xa9, 0xfe,
	0x56, 0xfe, 0x06, 0xe2, 0x69, 0xdc, 0xc9, 0xc3, 0xe9, 0xd2, 0x7c, 0x5f, 0xac, 0xce, 0x6e, 0xc2,
	0x46, 0xba, 0x0b, 0xcc, 0xd6, 0x7a, 0xf9, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x37, 0xd0, 0xc3, 0x17,
	0xc6, 0x04, 0x00, 0x00,
}
